export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const LOGOUT = 'LOGOUT';
export const FETCH_TOP_FIVE_HIGHLY_RATED_REVIEWS = 'FETCH_TOP_FIVE_HIGHLY_RATED_REVIEWS';
export const SHOW_SIGN_IN_ERROR_MESSAGE = 'SHOW_SIGN_IN_ERROR_MESSAGE';